version: '3.8'

services:
  backend_secure:
    env_file: ./backend_secure/database.conf
    build: ./backend_secure
    restart: always
    container_name: backend_secure
    ports:
      - "5003:5003"
    depends_on:
      - backend_secure_db
    volumes:
      - ./backend_secure:/app
  
  backend:
    env_file: ./backend/database.conf
    build: ./backend
    restart: always
    container_name: backend
    ports:
      - "5004:5004"
    depends_on:
      - backend_db
    volumes:
      - ./backend:/app

  backend_secure_db:
    container_name: backend_secure_db
    restart: always
    image: postgres:13.4
    env_file: ./backend_secure/database.conf
    ports:
      - "5434:5434"
  
  backend_db:
    container_name: backend_db
    restart: always
    image: postgres:13.4
    env_file: ./backend/database.conf
    ports:
      - "5432:5432"
